### ISSUE TITLE
multiSelectCheckboxPolls No Longer Working

### ISSUE THREAD

**Issue by jeisaacs** [pendo-io/snippets#27]
Hey Dev's

I have a bit of an issue in that the [multiSelectCheckboxPolls](https://github.com/pendo-io/snippets/tree/f9ec23439decb3addae60999e188cfdc345bc18c/guides/guidePolls/multiSelectCheckboxPolls) is no longer working.

Why Pendo haven't implemented this type of feature natively is beyond me, however it's something which I used a lot, and there is no workaround 😢

All the steps before work, however the one with the code does not display.

Pendo support has confirmed that the JavaScript snippet is the cause, but it falls outside their warranty or SLA of support.

Any help would be greatly appreciated.

**Comment by prolitariat** [comment]
Confirmed this solution worked. Thanks so much @jeisaacs! :)
