### ISSUE TITLE
Auto guides filtered out in guidesLoaded event are still showing 

### ISSUE THREAD

**Issue by cody-ryan-pope** [pendo-io/snippets#3]
https://github.com/pendo-io/snippets/blob/d2d1419fc8a6727f2f482065fc13bf8764e0a6a9/install/removeAutoGuides.js#L30-L41

Expected behavior:
When calling `pendo.initialize(options)` with the above options, we expect for all guides that have launchMethod 'auto' to be filtered out of the guides array.  We expect for these guides to not be automatically shown.

Actual behavior:
On calling `pendo.startGuides();`, these auto guides are still automatically shown.  Even when 
`pendo.guides = [];`, the auto guides are still shown when calling `pendo.startGuides();`

**Comment by kerbam** [comment]
This is a known issue on versions older than 2.8.0. I will update the comments to note the supported version of this snippet. Downgrading the agent to 2.8.0 should resolve the issue.

We currently do not have a workaround for newer agent versions but have a pending feature request to incorporate the functionality into the agent.
